/**
 * The Operating Range dataset.
 *
 * `x`/`y` are percentages of the collage image's box. They aren't hand-typed —
 * they were generated by scattering each discipline around an anatomical anchor
 * and rejecting any point that wasn't well inside the artwork's alpha
 * silhouette, so no marker can float off the edge or collide with a neighbour.
 * Regenerate them (rather than nudging by hand) if the artwork changes.
 *
 * `level` reads as marker size and as the tier meter in the readout: 3 is a
 * daily driver, 1 is working knowledge.
 */

export type DisciplineId = "core" | "interface" | "motion" | "systems" | "intelligence" | "delivery";

/**
 * The two brand accents, nothing else. Six lobes across two colours means the
 * pair repeats, so it's assigned to maximise contrast between *touching* lobes
 * — every close neighbour alternates; the only repeat is Motion/Core, the
 * farthest-apart pair on the map.
 */
export type Tint = "signal" | "lime";

export interface Discipline {
  id: DisciplineId;
  label: string;
  blurb: string;
  tint: Tint;
  /** Anatomical region this discipline is pinned to, shown as the map caption. */
  region: string;
  /**
   * Collage art for this discipline. All six share the brain for now; drop a
   * per-discipline cutout in here and the map cross-fades to it on select.
   */
  image: string;
}

export interface Skill {
  name: string;
  discipline: DisciplineId;
  /** One line, shown in the readout on hover. Present tense, no marketing. */
  note: string;
  level: 1 | 2 | 3;
  /** Marker position, percent of the artwork box. Generated — see above. */
  x: number;
  y: number;
}

export const BASE_ART = "/images/brain.webp";

export const DISCIPLINES: Discipline[] = [
  {
    id: "core",
    label: "Core",
    blurb: "The languages everything else is written in.",
    tint: "lime",
    region: "Temporal · foundation",
    image: BASE_ART,
  },
  {
    id: "interface",
    label: "Interface",
    blurb: "Turning a layout into a component system that survives the next feature.",
    tint: "signal",
    region: "Frontal · what you see",
    image: BASE_ART,
  },
  {
    id: "motion",
    label: "Motion",
    blurb: "Movement with a reason — and a frame budget.",
    tint: "lime",
    region: "Motor strip · movement",
    image: BASE_ART,
  },
  {
    id: "systems",
    label: "Systems",
    blurb: "Schemas, policies and endpoints behind the pretty part.",
    tint: "signal",
    region: "Parietal · integration",
    image: BASE_ART,
  },
  {
    id: "intelligence",
    label: "Intelligence",
    blurb: "Models that run on my machine and tools that write with me.",
    tint: "lime",
    region: "Occipital · reasoning",
    image: BASE_ART,
  },
  {
    id: "delivery",
    label: "Delivery",
    blurb: "Getting it live, fast, and findable.",
    tint: "signal",
    region: "Cerebellum · output",
    image: BASE_ART,
  },
];

export const SKILLS: Skill[] = [
  // ── Core ──────────────────────────────────────────────────────────────────
  { name: "TypeScript", discipline: "core", level: 3, note: "Strict mode by default. Types as the design doc.", x: 47, y: 58.3 },
  { name: "JavaScript", discipline: "core", level: 3, note: "Modern ES — modules, async, the DOM without a wrapper.", x: 37.5, y: 57.5 },
  { name: "HTML", discipline: "core", level: 3, note: "Semantic first. Landmarks, headings, real buttons.", x: 38.5, y: 63.3 },
  { name: "CSS", discipline: "core", level: 3, note: "Grid, container queries, custom properties, blend modes.", x: 44.6, y: 64.4 },
  { name: "Python", discipline: "core", level: 2, note: "Tooling and AI glue — Rudo's whole runtime.", x: 42.2, y: 55.9 },
  { name: "SQL", discipline: "core", level: 2, note: "Joins, indexes, and policies I can read back six months later.", x: 33.9, y: 62.7 },
  { name: "PowerShell", discipline: "core", level: 2, note: "Shipd is pure PowerShell — no modules, no telemetry.", x: 50.7, y: 61.8 },

  // ── Interface ─────────────────────────────────────────────────────────────
  { name: "React", discipline: "interface", level: 3, note: "19, with the concurrent bits used on purpose.", x: 26.6, y: 40.6 },
  { name: "Vite", discipline: "interface", level: 3, note: "Build config, chunk splitting, asset pipelines.", x: 19.8, y: 42.9 },
  { name: "Tailwind CSS", discipline: "interface", level: 3, note: "v4 with a real @theme token layer — no stray hex.", x: 23.7, y: 46.3 },
  { name: "Design Tokens", discipline: "interface", level: 3, note: "One palette, one type scale, zero hardcoded colour.", x: 22.2, y: 37.8 },
  { name: "Component Systems", discipline: "interface", level: 3, note: "Small files, clear seams, reuse before abstraction.", x: 29, y: 45.9 },
  { name: "Responsive Layout", discipline: "interface", level: 3, note: "Capability queries over width guesses.", x: 32, y: 39.5 },
  { name: "Custom Hooks", discipline: "interface", level: 3, note: "matchMedia, observers, rAF — logic out of the JSX.", x: 16, y: 39.7 },
  { name: "Next.js", discipline: "interface", level: 2, note: "App router when a site needs to be indexed properly.", x: 16.4, y: 47.2 },
  { name: "React Router", discipline: "interface", level: 2, note: "v7, with route-level code splitting.", x: 27.9, y: 34.9 },
  { name: "Accessibility", discipline: "interface", level: 2, note: "WCAG AA contrast, focus order, reduced-motion paths.", x: 18.3, y: 34.3 },

  // ── Motion ────────────────────────────────────────────────────────────────
  { name: "Motion", discipline: "motion", level: 3, note: "Framer Motion, layout animation, spring physics.", x: 46.2, y: 21.7 },
  { name: "GSAP", discipline: "motion", level: 3, note: "Timelines for anything with more than two beats.", x: 40.6, y: 18.2 },
  { name: "ScrollTrigger", discipline: "motion", level: 2, note: "Pinning and scrubbing that survives a resize.", x: 49.5, y: 17.6 },
  { name: "Three.js", discipline: "motion", level: 2, note: "Scenes, cameras, and knowing when not to use one.", x: 45, y: 16 },
  { name: "OGL / WebGL", discipline: "motion", level: 2, note: "Lighter than Three when all you need is a plane.", x: 41.9, y: 24.8 },
  { name: "Lenis", discipline: "motion", level: 2, note: "Smooth scroll on pointers, native momentum on touch.", x: 50.7, y: 23.4 },
  { name: "Canvas 2D", discipline: "motion", level: 2, note: "Game loops and generative fields at 60fps.", x: 36.8, y: 22.2 },
  { name: "SVG Motion", discipline: "motion", level: 2, note: "Path drawing, morphs, filter tricks.", x: 54.9, y: 19.6 },
  { name: "GLSL", discipline: "motion", level: 1, note: "Fragment shaders — enough to tune someone else's.", x: 47, y: 27.6 },

  // ── Systems ───────────────────────────────────────────────────────────────
  { name: "Supabase", discipline: "systems", level: 3, note: "Auth, Postgres, storage, edge functions.", x: 67.3, y: 24.2 },
  { name: "REST APIs", discipline: "systems", level: 3, note: "Designing them and consuming them without leaking state.", x: 64.9, y: 32.4 },
  { name: "PostgreSQL", discipline: "systems", level: 2, note: "Schema design, relations, migrations.", x: 60, y: 27.7 },
  { name: "Row-Level Security", discipline: "systems", level: 2, note: "RLS on every table. No exceptions.", x: 71.3, y: 27.4 },
  { name: "Node.js", discipline: "systems", level: 2, note: "Scripts, servers, and build-time tooling.", x: 70.2, y: 33 },
  { name: "Express", discipline: "systems", level: 2, note: "Routes, middleware, the boring reliable layer.", x: 62.4, y: 22.7 },
  { name: "Edge Functions", discipline: "systems", level: 2, note: "Deno-side logic that can't live in the client.", x: 60.4, y: 34 },
  { name: "Auth / OAuth", discipline: "systems", level: 2, note: "Google sign-in, sessions, role-based access.", x: 74.8, y: 31.6 },
  { name: "Sanity", discipline: "systems", level: 1, note: "Structured content when a client needs to edit it.", x: 71.3, y: 21 },

  // ── Intelligence ──────────────────────────────────────────────────────────
  { name: "Claude Code", discipline: "intelligence", level: 3, note: "Agents, subagents, hooks, and skills in the loop.", x: 81.9, y: 49.8 },
  { name: "Cursor", discipline: "intelligence", level: 3, note: "Daily driver for the fast, boring edits.", x: 84, y: 41.9 },
  { name: "Ollama", discipline: "intelligence", level: 2, note: "Local model runtime — no keys, no rate limits.", x: 78.8, y: 44.4 },
  { name: "Gemma 3", discipline: "intelligence", level: 2, note: "Rudo runs on it, fully offline.", x: 88.8, y: 44.6 },
  { name: "Local LLMs", discipline: "intelligence", level: 2, note: "Tool calling, streaming, persistent memory.", x: 86.5, y: 50.5 },
  { name: "Prompt Design", discipline: "intelligence", level: 2, note: "Context engineering beats prompt tricks.", x: 76.3, y: 49.5 },

  // ── Delivery ──────────────────────────────────────────────────────────────
  { name: "Git", discipline: "delivery", level: 3, note: "Atomic commits, readable history, no force pushes.", x: 60.2, y: 74.1 },
  { name: "Vercel", discipline: "delivery", level: 3, note: "Push to main, ship to prod.", x: 65.9, y: 76.7 },
  { name: "Code Splitting", discipline: "delivery", level: 3, note: "Lazy routes and deferred sections — this page does it.", x: 60.4, y: 80 },
  { name: "Cloudflare Pages", discipline: "delivery", level: 2, note: "Where this site actually lives.", x: 64.6, y: 70.8 },
  { name: "Figma", discipline: "delivery", level: 2, note: "Enough to design it, plenty to build from it.", x: 70.4, y: 74.9 },
  { name: "Lighthouse", discipline: "delivery", level: 2, note: "Chased to green on real hardware, not a lab score.", x: 65.4, y: 82.6 },
  { name: "Image Pipelines", discipline: "delivery", level: 2, note: "sharp, WebP, and sizes that match the layout.", x: 55.9, y: 76.4 },
  { name: "SEO", discipline: "delivery", level: 2, note: "Canonicals, sitemaps, OG tags, structured data.", x: 71.2, y: 81.2 },
  { name: "Sentry", discipline: "delivery", level: 1, note: "Error reporting on the things clients pay for.", x: 69.1, y: 69.3 },
];

export const DISCIPLINE_BY_ID = new Map(DISCIPLINES.map((d) => [d.id, d]));

export function countFor(id: DisciplineId): number {
  return SKILLS.filter((s) => s.discipline === id).length;
}
