import { Project, Poster, Thought, TimelineItem } from "./types";

export const PROJECTS: Project[] = [
  // — Websites —
  {
    id: "velsaro",
    number: "01",
    title: "VELSARO",
    category: "websites",
    role: "Frontend Developer",
    year: "2026",
    status: "Shipped",
    description: "Luxury fragrance e-commerce platform combining modern frontend development, secure authentication, database integration and scalable application architecture.",
    tags: ["React", "TypeScript", "Tailwind CSS", "Supabase", "Vite"],
    visual: "/images/velsaro.webp",
    liveUrl: "https://www.velsaro.in/",
    detail: {
      cover: "/images/velsaro.webp",
      paragraphs: [
        "A luxury fragrance e-commerce platform built from the ground up. From authentication to checkout, every component was designed with both aesthetics and performance in mind. The result is a shopping experience that feels as premium as the products it sells.",
        "Supabase handles the backend — user auth, product inventory, and order management are all managed through a robust PostgreSQL schema. Role-based access controls ensure the right people see the right data, while the real-time capabilities enable live inventory updates.",
        "The frontend is built with React and TypeScript, styled with Tailwind CSS. Every page is responsive, every transition is smooth, and every image is optimized for fast loading. The component library was built from scratch to ensure consistency across the entire platform.",
        "What started as a simple storefront evolved into a full-fledged e-commerce system with inventory tracking, admin dashboards, and a seamless user experience. This project taught me the importance of balancing feature richness with performance.",
      ],
    },
  },
  {
    id: "nexcart",
    number: "02",
    title: "NEXCART",
    category: "websites",
    role: "Frontend Developer",
    year: "2026",
    status: "Shipped",
    description: "Modern commerce application focused on reusable components, responsive layouts, API integration and performance optimisation.",
    tags: ["React", "Tailwind CSS", "TypeScript", "REST API"],
    visual: "/images/nexcart.webp",
    liveUrl: "https://nexcart-v1.vercel.app/",
    detail: {
      cover: "/images/nexcart.webp",
      paragraphs: [
        "A modern commerce application focused on reusable component architecture. The goal was to build a shopping experience that feels both familiar and fresh, with a clean design language that scales across the entire product catalog.",
        "API integration was a key focus — fetching products, managing cart state, and handling checkout flows all required careful state management. Custom hooks keep the logic clean and testable, while the REST API layer abstracts away backend complexity.",
        "The responsive layout adapts seamlessly from mobile to desktop, with careful attention to touch interactions and gesture-based navigation. Every breakpoint was considered, every edge case handled.",
        "Performance optimisation was a constant priority. Lazy loading, code splitting, and image optimisation keep the app snappy even on slower connections. The final build is lean, fast, and ready for production.",
      ],
    },
  },
  {
    id: "synapical",
    number: "03",
    title: "SYNAPICAL",
    category: "websites",
    role: "Design & Frontend",
    year: "2026",
    status: "Shipped",
    description: "Landing site for a Delhi software studio — a bold editorial hero, a floating 3D browser mockup, and motion-driven storytelling built to convert.",
    tags: ["React", "Three.js", "GSAP", "Tailwind CSS"],
    visual: "/images/synapical.webp",
    liveUrl: "https://synapical-com.pages.dev/",
    detail: {
      cover: "/images/synapical.webp",
      paragraphs: [
        "Synapical needed a first impression that matched the work — a small studio that ships web, mobile, AI, and cloud. The hero leads with a single confident claim and a live 3D browser mockup, setting the tone before a visitor scrolls a single pixel.",
        "The layout is unapologetically editorial: oversized display type, a coordinate-marked masthead, and generous negative space. Every section is anchored to a strict grid so the density feels intentional rather than busy.",
        "Motion carries the narrative. GSAP-driven reveals, a parallax hero object, and micro-interactions on the calls-to-action keep the page feeling alive without ever getting in the way of the message.",
        "The result is a site that reads as a product, not a brochure — fast, responsive, and built so new case studies and services can be dropped in without touching the design system.",
      ],
    },
  },
  {
    id: "attendo",
    number: "04",
    title: "ATTENDO",
    category: "websites",
    role: "Full-Stack Developer",
    year: "2026",
    status: "Shipped",
    description: "College attendance system with a dedicated dashboard per role — students, faculty and admins — with every access rule enforced in Postgres, not just the UI.",
    tags: ["TanStack Start", "TypeScript", "Supabase", "shadcn/ui", "Tailwind CSS"],
    visual: "/images/attendo.webp",
    liveUrl: "https://attendov1.vercel.app/",
    repoUrl: "https://github.com/harsh4k/attendov1",
    detail: {
      cover: "/images/attendo.webp",
      paragraphs: [
        "Attendo (\"Project Revive\") gives every seat in a college attendance system its own dashboard — students track lecture-by-lecture history and defaulter status, faculty schedule and mark lectures, and admins manage users, roles and faculty-subject assignments from one place.",
        "Every rule lives in the database, not the UI. Role-based auth splits student, faculty and admin access, and row-level security in Postgres enforces marking windows and visibility at the data layer — the interface can't accidentally show or edit what a role shouldn't touch.",
        "Built on TanStack Start, Router and Query over a Vite + React + TypeScript base, with shadcn/ui's Radix primitives and Tailwind for the interface, react-hook-form and Zod on every form, and Bun running the toolchain.",
        "Underneath, the schema tracks profiles, subjects, faculty-subject assignments, enrollments, and lectures through their full lifecycle — scheduled, ongoing, completed, cancelled — with attendance and notifications layered on top.",
      ],
    },
  },
  {
    id: "coffee-digital",
    number: "05",
    title: "COFFEE DIGITAL",
    category: "websites",
    role: "Frontend Developer",
    year: "2026",
    status: "Shipped",
    description: "Rebrand of a scraped agency mirror into Coffee Digital's own site — same inherited layout and motion, entirely new content, branding, palette and typography, shipped as flat pre-compiled output with no build step.",
    tags: ["Next.js", "Playwright", "Vercel"],
    visual: "/images/coffee-digital.webp",
    liveUrl: "https://coffeedigital.vercel.app/",
    detail: {
      cover: "/images/coffee-digital.webp",
      paragraphs: [
        "Coffee Digital needed a site fast, and the fastest path was honest about its own shortcut: start from a scraped mirror of another agency's layout and motion, then replace everything that makes it theirs — content, branding, palette, typography.",
        "The result is unusual under the hood. It's not a React or Vite project — it's roughly 60MB of pre-compiled Next.js output served as flat files, with no build step and no bundler. Editing it means touching compiled markup directly, not JSX.",
        "The hero commits to a single line — \"Designed to mean something\" — over a chrome-rendered 3D bean mark, with a locally-run Python server for development and Vercel for deploy.",
        "It's a study in constraint: ship a brand-accurate site under a layout you didn't design, on a stack that punishes the usual instincts of \"edit the JSX, run the dev server.\"",
      ],
    },
  },
  {
    id: "coffee-rebuild",
    number: "06",
    title: "COFFEE DIGITAL — REBUILD",
    category: "websites",
    role: "Design & Frontend",
    year: "2026",
    status: "In progress",
    description: "Ground-up rebuild of the same brand — heavy scroll-driven motion, a warm off-white ground and a WebGL bean, built from scratch rather than inherited.",
    tags: ["Next.js 16", "Three.js", "React Spring", "Tailwind CSS", "Lenis"],
    visual: "/images/coffee-rebuild.webp",
    liveUrl: "https://threedwebs.vercel.app/",
    repoUrl: "https://github.com/harsh4k/3dwebs",
    detail: {
      cover: "/images/coffee-rebuild.webp",
      paragraphs: [
        "Where the shipped Coffee Digital site inherits its layout, this is the same brand rebuilt from first principles — Next.js 16, Tailwind v4, three.js and react-spring, with Lenis driving a heavy scroll-based motion language across the home page and /work.",
        "The page ground itself tells the story: it walks from #FFFAF3 to #FFE5BF as you scroll, warming light to dark like a roast developing — one of a handful of signature devices built specifically for this brand rather than borrowed from a reference.",
        "The logo's half-filled counter — \"the Bean\" — carries the identity everywhere: as the cursor, the loader, and the subject of a baked point-cloud particle scene in the WebGL hero. Work cards resolve into focus out of a Bayer dither rather than a plain fade.",
        "Home and /work are built; services, about and contact are still stubs. Heat is rationed deliberately — one signal-red element per viewport — so the palette stays disciplined as more pages come online.",
      ],
    },
  },

  // — Fun Code —
  {
    id: "oysnk",
    number: "01",
    title: "OYSNK",
    category: "fun",
    role: "Frontend Developer",
    year: "2026",
    status: "Shipped",
    description: "Experimental web application exploring interaction systems, creative development and modern software architecture.",
    tags: ["Next.js", "CSS", "GSAP", "Tailwind CSS"],
    visual: "/images/Osynk.webp",
    liveUrl: "https://oysnk.vercel.app/",
    detail: {
      cover: "/images/Osynk.webp",
      paragraphs: [
        "An experimental playground where creative development meets interaction design. No constraints, no briefs — just pure exploration of what the web can do when you push beyond conventional patterns.",
        "The project experiments with scroll-triggered animations, dynamic layouts, and unconventional UI patterns. GSAP powers the motion, while CSS handles the visual polish. Every interaction was designed to surprise and delight.",
        "From cursor effects to page transitions, the goal was to create something that feels alive. The result is a digital experience that rewards exploration and challenges expectations.",
        "This project taught me that the best ideas often come from stepping outside the boundaries of conventional web development. Sometimes the most valuable thing you can build is something purely for the joy of building it.",
      ],
    },
  },
  {
    id: "shipd",
    number: "02",
    title: "SHIPD",
    category: "fun",
    role: "Systems / Tooling",
    year: "2026",
    status: "Shipped",
    description: "A daily dev + activity report for Windows, written in pure PowerShell — no dependencies, no accounts, no telemetry. Every byte stays on your machine.",
    tags: ["PowerShell", "Windows", "Git", "Automation"],
    visual: "/images/shipd.webp",
    repoUrl: "https://github.com/harsh4k/shipd",
    detail: {
      cover: "/images/shipd.webp",
      paragraphs: [
        "Shipd snapshots what you actually did all day. Every ten minutes it records the app in focus, idle time, and any running games, then rolls it all into an evening report that sits alongside your git commits across every project.",
        "It's deliberately zero-footprint: pure PowerShell, no external modules, no cloud sync. The data never leaves the folder it lives in — a privacy-first take on quantified-self tooling.",
        "A live terminal dashboard renders the day's metrics, while Task Scheduler integration keeps the tracker running quietly in the background. Snapshot cadence and report timing are both configurable.",
        "It also handles the housekeeping — a RAM breakdown and standby-cache clearing — so the same tool that measures your machine helps keep it fast.",
      ],
    },
  },
  {
    id: "rudo",
    number: "03",
    title: "RUDO",
    category: "fun",
    role: "AI / Tooling",
    year: "2026",
    status: "Shipped",
    description: "A Jarvis-style personal AI assistant running fully local on Gemma 3 via Ollama, wrapped in an animated terminal chat UI.",
    tags: ["Python", "Ollama", "Gemma 3", "AI"],
    visual: "/images/rudo.webp",
    repoUrl: "https://github.com/harsh4k/rudo",
    detail: {
      cover: "/images/rudo.webp",
      paragraphs: [
        "Rudo is a conversational companion that never leaves your machine. Gemma 3 runs locally through Ollama, so every reply is private and offline — no API keys, no rate limits, no data leaving the room.",
        "The terminal interface streams responses with live markdown and code rendering, opens with an animated boot sequence, and keeps a persistent memory of the conversation across sessions.",
        "Tool access turns it from a chatbot into an assistant: it can run shell commands, search the web via DuckDuckGo, read files, set timers, and index notes for semantic search.",
        "Live system awareness — CPU, RAM, battery, time — is baked into the status bar, so Rudo always answers with context about the machine it's running on.",
      ],
    },
  },
  {
    id: "bunny-os",
    number: "04",
    title: "BUNNY OS",
    category: "fun",
    role: "Full-Stack / Systems",
    year: "2026",
    status: "v0.3.4 Beta",
    description: "A local voice helper for Windows and Mac — hold F9 and talk to a top-edge island UI, powered entirely by on-device speech and chat models.",
    tags: ["Tauri", "React", "TypeScript", "Rust", "Python"],
    visual: "/images/bunny-os.webp",
    liveUrl: "https://harsh4k.github.io/Bunny-OS/",
    repoUrl: "https://github.com/harsh4k/Bunny-OS",
    detail: {
      cover: "/images/bunny-os.webp",
      paragraphs: [
        "Bunny OS lives in a sleek top-edge island that expands when you hold F9 and talk — or say an optional wake phrase — then opens apps, searches YouTube, hits media keys, or just chats, all without an account or a Bunny cloud.",
        "Speech and chat both run locally: faster-whisper handles transcription and Ollama runs the conversational model, so nothing leaves the machine. Raw microphone audio is never written to disk, and any risky action needs an on-screen confirm first.",
        "The stack is Tauri v2 wrapping a React/TypeScript frontend around a Rust core, with a Python sidecar for the local ML work. It shipped through 0.3.0 to 0.3.4 across August 2026 — voice finish, a light glass UI, an Apps dock, and fixes to the island's transparency and click-through behaviour.",
        "Optional Memory and Screen context exist but stay off until you turn them on, and an in-app updates board lets you check versions yourself rather than pushing silent auto-installs.",
      ],
    },
  },
  {
    id: "getcited",
    number: "05",
    title: "GETCITED",
    category: "fun",
    role: "Full-Stack Developer",
    year: "2026",
    status: "Hackathon Build",
    description: "AEO/GEO platform that audits how well AI assistants can read and cite a website, then generates copy-pasteable fixes.",
    tags: ["Next.js", "Supabase", "Python / Flask", "CLIP + DeepGaze"],
    visual: "/images/getcited.webp",
    repoUrl: "https://github.com/harsh4k/Getcited",
    detail: {
      cover: "/images/getcited.webp",
      paragraphs: [
        "GetCited scores a website the way an AI assistant reads it, not the way a search-engine crawler does — technical structure, semantic content, metadata and authority signals, then a citation-readiness score and prioritized fixes.",
        "A four-step pipeline understands the page, finds the questions it could get cited for, maps those to likely AI queries, and generates optimized, copy-pasteable writeups for each one.",
        "The frontend is Next.js App Router with Supabase for auth and data; a separate Python Flask service handles visual saliency scoring with CLIP and DeepGaze, ad-hotspot detection, and sitemap crawling for page discovery.",
        "Built with team TheTokenizers for the NamasteDev Hackathon 2026, with rate limiting on every AI endpoint and a mobile-responsive dashboard covering audit history, A/B profiles and billing.",
      ],
    },
  },
];

export const POSTERS: Poster[] = [
  {
    id: "poster-1",
    number: "04",
    image: "/images/p1.webp",
    keywords: ["Grid", "Bold", "Minimal", "Contrast"],
    tagline: "Less is more — typography as structure.",
  },
  {
    id: "poster-2",
    number: "05",
    image: "/images/p2.webp",
    keywords: ["Type", "Scale", "Rhythm", "Space"],
    tagline: "Let the letters breathe and the layout follow.",
  },
  {
    id: "poster-3",
    number: "06",
    image: "/images/p3.webp",
    keywords: ["Mono", "Form", "Texture", "Layer"],
    tagline: "Shape and counter-shape in perfect balance.",
  },
  {
    id: "poster-4",
    number: "07",
    image: "https://picsum.photos/seed/poster-wave/800/1000?grayscale",
    keywords: ["Wave", "Motion", "Flow", "Gradient"],
    tagline: "Static on the surface. Moving underneath.",
  },
];

export const THOUGHTS: Thought[] = [
  {
    id: "thought-1",
    number: "01",
    title: "Build Over Theory",
    body: "Ship projects, not tutorials. Every idea becomes something real, something deployed, something that works.",
    tag: "Motto",
    image: "/images/t1.webp",
  },
  {
    id: "thought-2",
    number: "02",
    title: "Attention To Detail",
    body: "The premium feel isn't accidental. Typography, spacing, animation, layout: every pixel placed with intent.",
    tag: "Process",
  },
  {
    id: "thought-3",
    number: "03",
    title: "Finish Beats Perfect",
    body: "A shipped v1 teaches more than a perfect draft. Version 2.6 exists because 1.0 went out the door.",
    tag: "Discipline",
  },
  {
    id: "thought-4",
    number: "04",
    title: "Curiosity Over Comfort",
    body: "Linux, AI tooling, Three.js, GSAP, backends, new workflows. The stack grows when you stay curious.",
    tag: "Mindset",
    image: "/images/t2.webp",
  },
  {
    id: "thought-5",
    number: "05",
    title: "Own The Stack",
    body: "Local models, no telemetry, no vendor lock. If it runs on my machine, it keeps running when the service goes down.",
    tag: "Autonomy",
  },
  {
    id: "thought-6",
    number: "06",
    title: "Works Without Signal",
    body: "Fast on good wifi is easy. The real work is holding up on a dead connection, an old phone, a train tunnel.",
    tag: "Craft",
    image: "/images/t3.webp",
  },
];

export const TIMELINE: TimelineItem[] = [
  {
    year: "2024",
    title: "FUN FIRST",
    description: "Learning was chaotic. So was everything else. Wouldn't change it."
  },
  {
    year: "2025",
    title: "LOCKED IN",
    description: "Long nights. Hackathons. Good people. Great memories."
  },
  {
    year: "2026",
    title: "PERSPECTIVE",
    description: "Sometimes stepping away helps you move forward."
  }
];
