/// <reference types="vite/client" />
/// <reference types="vite-plugin-pwa/client" />

/**
 * Build-time list of heavy public assets, generated by the `offline-assets`
 * plugin in vite.config.ts. Kept virtual so it can't drift from public/images.
 */
declare module "virtual:offline-assets" {
  const urls: string[];
  export default urls;
}
